package com.hms.common.config;

import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

@Component
@RequiredArgsConstructor
@Slf4j
public class DataInitializer implements CommandLineRunner {

    @PersistenceContext
    private final EntityManager entityManager;

    @Override
    @Transactional
    public void run(String... args) {
        log.info("Starting database column initialization...");

        try {
            int versionCount = 0;
            versionCount += initializeVersionColumn("users");
            versionCount += initializeVersionColumn("revoked_refresh_tokens");
            versionCount += initializeVersionColumn("patients");
            versionCount += initializeVersionColumn("doctors");
            versionCount += initializeVersionColumn("appointments");
            versionCount += initializeVersionColumn("medicines");
            versionCount += initializeVersionColumn("inventory_transactions");
            versionCount += initializeVersionColumn("prescriptions");
            versionCount += initializeVersionColumn("billings");
            if (versionCount > 0) {
                log.info("Initialized {} null entity version fields", versionCount);
            }

            int userCount = entityManager.createQuery(
                    "UPDATE User u SET u.tokenVersion = 0 WHERE u.tokenVersion IS NULL")
                    .executeUpdate();
            userCount += entityManager.createQuery(
                    "UPDATE User u SET u.enabled = true WHERE u.enabled IS NULL")
                    .executeUpdate();
            userCount += entityManager.createQuery(
                    "UPDATE User u SET u.passwordChangeRequired = false WHERE u.passwordChangeRequired IS NULL")
                    .executeUpdate();
            if (userCount > 0) {
                log.info("Initialized {} User-specific primitive fields", userCount);
            }
            
            // Fix Doctor fields (department and specialization)
            int doctorCount = entityManager.createQuery(
                    "UPDATE Doctor d SET d.department = 'GENERAL_MEDICINE' WHERE d.department IS NULL")
                    .executeUpdate();
            
            doctorCount += entityManager.createQuery(
                    "UPDATE Doctor d SET d.specialization = 'General Medicine' WHERE d.specialization = 'General'")
                    .executeUpdate();

            doctorCount += repairAutoGeneratedDoctorNames();
            
            if (doctorCount > 0) {
                log.info("Repaired {} Doctor profile fields for system compatibility", doctorCount);
            }
        } catch (Exception e) {
            log.warn("Failed to initialize database fields: {}", e.getMessage());
        }

        log.info("Database column initialization completed.");
    }

    private int initializeVersionColumn(String tableName) {
        try {
            Number columnCount = (Number) entityManager.createNativeQuery("""
                            SELECT COUNT(*)
                            FROM information_schema.columns
                            WHERE table_schema = DATABASE()
                              AND table_name = :tableName
                              AND column_name = 'version'
                            """)
                    .setParameter("tableName", tableName)
                    .getSingleResult();

            if (columnCount.intValue() == 0) {
                return 0;
            }

            return entityManager.createNativeQuery("UPDATE " + tableName + " SET version = 0 WHERE version IS NULL")
                    .executeUpdate();
        } catch (Exception e) {
            log.debug("Skipping version initialization for table {}: {}", tableName, e.getMessage());
            return 0;
        }
    }

    private int repairAutoGeneratedDoctorNames() {
        try {
            return entityManager.createNativeQuery("""
                            UPDATE doctors d
                            JOIN users u ON d.user_id = u.id
                            SET d.first_name = CASE
                                    WHEN INSTR(u.username, '.') > 0 THEN SUBSTRING_INDEX(u.username, '.', 1)
                                    ELSE u.username
                                END,
                                d.last_name = CASE
                                    WHEN INSTR(u.username, '.') > 0 THEN SUBSTRING_INDEX(u.username, '.', -1)
                                    ELSE 'Profile'
                                END
                            WHERE d.last_name IN ('(Auto-Generated)', 'Auto Generated')
                            """)
                    .executeUpdate();
        } catch (Exception firstAttempt) {
            try {
                return entityManager.createNativeQuery("""
                                UPDATE doctors d
                                JOIN users u ON d.userId = u.id
                                SET d.firstName = CASE
                                        WHEN INSTR(u.username, '.') > 0 THEN SUBSTRING_INDEX(u.username, '.', 1)
                                        ELSE u.username
                                    END,
                                    d.lastName = CASE
                                        WHEN INSTR(u.username, '.') > 0 THEN SUBSTRING_INDEX(u.username, '.', -1)
                                        ELSE 'Profile'
                                    END
                                WHERE d.lastName IN ('(Auto-Generated)', 'Auto Generated')
                                """)
                        .executeUpdate();
            } catch (Exception secondAttempt) {
                log.debug("Skipping auto-generated doctor name repair: {}", secondAttempt.getMessage());
                return 0;
            }
        }
    }
}
